### ISSUE TITLE
Crashes at high sampling rates

### ISSUE THREAD

**Issue by arinabykadorova** [project8/locust_mc#233]
When Locust is run at high sampling rates, it often crashes before filling a time slice. In this mode, the decimation factor is set to 1 and Locust is re-compiled. Then the acquisition rate is set to 64 GHz, and the LO and LPF turned off.
After some number of samples, the fields and voltages become NANs.
It appears to be a memory leak, because if I increase available RAM, the problem seems to lessen.

**Comment by pslocum** [comment]
Thanks for reporting this issue.  Please compile any other related information in this thread, as it becomes available.  This will help with diagnostics.

**Comment by pslocum** [comment]
I have not been able to detect a memory leak that could explain this behavior.  However, given the very high sampling rates that seem to cause the issue, it may be that the problem could be mitigated or fixed by the proposed 2-way trigger, here:  https://github.com/project8/locust_mc/issues/246 .  Suggesting to close this for now as an effective merge with https://github.com/project8/locust_mc/issues/246 .  If new relevant information becomes available, please open a new issue and link to this one for history and tracking.
